FROM wikibase/wikibase-bundle:1.35.4-wmde.2

# Install utilities
#RUN apt-get update && apt-get install -y \
#  git less

#COPY ./LocalSettings.override.php /var/www/html/LocalSettings.d/

# Install Math extension
#RUN \
#git clone -b REL1_35 "https://gerrit.wikimedia.org/r/mediawiki/extensions/Math" extensions/Math \
#&& echo 'wfLoadExtension( 'Math' );' >> /var/www/html/LocalSettings.d/LocalSettings.override.php