http:
  routers:
    to-chat:
      rule:  Host(`chat.portal.mardi4nfdi.de`)
      service: chat
      entryPoints: [websecure]
      tls:
        certResolver: le
  services:
    # Define how to reach an existing service on our infrastructure
    chat:
      loadBalancer:
        servers:
        - url: http://130.73.240.218
