http:
  services:
    whoisswarm:
      loadBalancer:
        servers:
        - url: "http://10.0.2.17"
        
  routers:
    whoami-router:
      rule: Host(`who.portal.mardi4nfdi.de`)
      service: whoisswarm
      entryPoints: [websecure]
      tls:
        certResolver: le
