{
 "title": "Backup monitor",
 "time": { "from": "2022-03-27T22:00:00.000Z", "to": "now" },
 "panels": [
  { "title": "Backup status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup current status",
   "type": "stat",
   "description": "status code of backup: 0 = success, 1 = error",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_last_status_code", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - backup_last_time_seconds"
    }
   ]
  },
  {
   "title": "Date of last backup",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "backup_last_time_seconds * 1000"
    }
   ]
  },
  {
   "title": "Backup status history",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "expr": "backup_last_status_code", "legendFormat": "{{ type }}" }
   ]
  },
  { "title": "Backup storage stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Disk usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{device=\"/dev/mapper/vg_salt-data\", mountpoint=\"/srv\"} / node_filesystem_size_bytes{device=\"/dev/mapper/vg_salt-data\", mountpoint=\"/srv\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Storage disk space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/mapper/vg_salt-data\", mountpoint=\"/srv\"} - node_filesystem_avail_bytes{device=\"/dev/mapper/vg_salt-data\", mountpoint=\"/srv\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/mapper/vg_salt-data\", mountpoint=\"/srv\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Size of last backup",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "backup_last_size_bytes", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Total backup size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "backup_total_size_bytes", "legendFormat": "Total size" }
   ]
  }
 ]
}